"""Forecast inputs assembled from the user's data, then handed to the pure core.

Plain functions over a session (no repository interfaces — see ARCHITECTURE.md),
all scoped by `user_id`. The projection arithmetic lives in
`app.shared.domain.forecast`; this module only gathers its three inputs:

  1. start balance  — sum of all account balances today,
  2. scheduled      — recurring income/bills dated within the horizon,
  3. avg daily net  — trailing discretionary spend (non-recurring expenses).
"""

import uuid
from datetime import date, timedelta

from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select

from app.modules.accounts.service import list_accounts
from app.modules.bills.service import list_rules
from app.modules.transactions.models import Transaction
from app.modules.transactions.service import account_deltas
from app.shared.domain.forecast import ForecastResult, forecast
from app.shared.domain.recurring import occurrences_between

_HISTORY_WINDOW_DAYS = 90


async def _start_balance(session: AsyncSession, user_id: uuid.UUID) -> float:
    accounts = await list_accounts(session, user_id, include_archived=True)
    deltas = await account_deltas(session, user_id)
    return sum(a.opening_balance for a in accounts) + sum(deltas.values())


async def _scheduled(
    session: AsyncSession, user_id: uuid.UUID, start: date, end: date
) -> dict[str, float]:
    """Signed recurring events per date within (start, end]. Transfers net zero."""
    scheduled: dict[str, float] = {}
    for rule in await list_rules(session, user_id):
        if rule.type == "transfer":
            continue
        sign = 1.0 if rule.type == "income" else -1.0
        dates = occurrences_between(
            rule.next_run, rule.frequency, rule.interval, start, end, rule.end_date
        )
        for occ in dates:
            key = occ.isoformat()
            scheduled[key] = scheduled.get(key, 0.0) + sign * rule.amount
    return scheduled


async def _avg_daily_net(session: AsyncSession, user_id: uuid.UUID, today: date) -> float:
    """Average daily discretionary spend over the trailing window (negative).

    Discretionary = expenses not generated by a recurring rule (those are already
    counted in `scheduled`), so the two inputs don't double-count.
    """
    window_start = today - timedelta(days=_HISTORY_WINDOW_DAYS)
    stmt = select(Transaction).where(
        Transaction.user_id == user_id,
        Transaction.deleted == False,  # noqa: E712
        Transaction.type == "expense",
        Transaction.recurring_id == None,  # noqa: E711
        Transaction.date >= window_start,
        Transaction.date <= today,
    )
    rows = (await session.execute(stmt)).scalars().all()
    total = sum(t.amount for t in rows)
    return -(total / _HISTORY_WINDOW_DAYS)


async def build_forecast(
    session: AsyncSession, user_id: uuid.UUID, horizon: int, today: date | None = None
) -> ForecastResult:
    now = today or date.today()
    start_balance = await _start_balance(session, user_id)
    scheduled = await _scheduled(session, user_id, now, now + timedelta(days=horizon))
    avg = await _avg_daily_net(session, user_id, now)
    return forecast(start_balance, now, horizon, scheduled, avg)


async def forecast_inputs(
    session: AsyncSession, user_id: uuid.UUID, today: date | None = None
) -> tuple[float, float]:
    """(start_balance, avg_daily_net) — surfaced alongside the projection."""
    now = today or date.today()
    return await _start_balance(session, user_id), await _avg_daily_net(session, user_id, now)
