"""add merchant table

Revision ID: 4249b08b569c
Revises: 50ec9073dc1b
Create Date: 2026-07-02 12:35:47.719157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = '4249b08b569c'
down_revision: Union[str, None] = '50ec9073dc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('recurring_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_user_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_deleted'))
        batch_op.drop_index(batch_op.f('ix_merchant_category_id'))

    op.drop_table('merchant')
    # ### end Alembic commands ###
