"""add account table

Revision ID: 4c134130c910
Revises: e97f1e5f3a53
Create Date: 2026-07-02 10:37:24.362172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = '4c134130c910'
down_revision: Union[str, None] = 'e97f1e5f3a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_deleted'))

    op.drop_table('account')
    # ### end Alembic commands ###
