"""add asset liability net_worth_snapshot tables

Revision ID: 4dd37c30c894
Revises: 2abe2b936599
Create Date: 2026-07-02 21:20:36.560004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = '4dd37c30c894'
down_revision: Union[str, None] = '2abe2b936599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_user_id'), ['user_id'], unique=False)

    op.create_table('liability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liability_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_user_id'), ['user_id'], unique=False)

    op.create_table('net_worth_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('assets_total', sa.Float(), nullable=False),
    sa.Column('liabilities_total', sa.Float(), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('net_worth_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_net_worth_snapshot_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_net_worth_snapshot_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_net_worth_snapshot_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_worth_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshot_user_id'))
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshot_deleted'))
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshot_date'))

    op.drop_table('net_worth_snapshot')
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liability_user_id'))
        batch_op.drop_index(batch_op.f('ix_liability_deleted'))

    op.drop_table('liability')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_deleted'))

    op.drop_table('asset')
    # ### end Alembic commands ###
