"""add transaction table

Revision ID: 50ec9073dc1b
Revises: 4c134130c910
Create Date: 2026-07-02 10:41:58.611156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = '50ec9073dc1b'
down_revision: Union[str, None] = '4c134130c910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_account_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('recurring_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_recurring_id'), ['recurring_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transfer_account_id'), ['transfer_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_transfer_account_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_recurring_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_deleted'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_category_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    op.drop_table('transaction')
    # ### end Alembic commands ###
