"""add recurring_rule table

Revision ID: 5f7f188f4b8e
Revises: 4249b08b569c
Create Date: 2026-07-02 12:46:59.246751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = '5f7f188f4b8e'
down_revision: Union[str, None] = '4249b08b569c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_account_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_run', sa.Date(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rule_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_next_run'), ['next_run'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_start_date'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_next_run'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_deleted'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_account_id'))

    op.drop_table('recurring_rule')
    # ### end Alembic commands ###
