"""add receipt_import table

Revision ID: b4caf8d99b62
Revises: d3e4f5a6b7c8
Create Date: 2026-07-08 12:16:34.713816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in migrations


# revision identifiers, used by Alembic.
revision: str = 'b4caf8d99b62'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_import',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('draft_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('linked_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_import_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_import_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_import_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_import_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_import_status'))
        batch_op.drop_index(batch_op.f('ix_receipt_import_content_hash'))

    op.drop_table('receipt_import')
    # ### end Alembic commands ###
